name: Android CI

on:
  push:
    branches:
      - main # Or your default branch like 'master'
  pull_request:
    branches:
      - main # Or your default branch like 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle (Release)
        run: ./gradlew assembleRelease

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          # Use a wildcard - this is often safer if the filename changes based on version,
          # as long as only one APK is expected in this directory.
          path: app/build/outputs/apk/release/*.apk
