name: Android CI # 工作流的名称

on:
  push: # 在 push 事件时触发
    branches: # 指定触发的分支
      - main
      - develop
  pull_request: # 在 pull request 事件时触发
    branches: # 指定触发的分支
      - main
      - develop

jobs:
  build: # 定义一个名为 build 的作业
    runs-on: ubuntu-latest # 指定作业运行的操作系统环境

    steps:
      - uses: actions/checkout@v4 # 检出代码库

      - name: Set up JDK 17 # 设置 Java Development Kit 为版本 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # 使用 Temurin 发行版
          java-version: '17' # 指定 Java 版本

      - name: Grant execute permission for gradlew # 授予 gradlew 脚本执行权限
        run: chmod +x gradlew

      - name: Build Debug APK # 构建 Debug 版本的 APK
        run: ./gradlew assembleDebug

      - name: Upload Debug APK # 上传 Debug 版本的 APK 作为构建产物
        uses: actions/upload-artifact@v4
        with:
          name: app-debug # 产物的名称
          path: app/build/outputs/apk/debug/app-debug.apk # Debug APK 的路径

      - name: Build Release APK # 构建 Release 版本的 APK
        run: ./gradlew assembleRelease

      - name: Upload Release APK # 上传 Release 版本的 APK 作为构建产物
        uses: actions/upload-artifact@v4
        with:
          name: SEI804_VideoInfoOverlay_21.0.apk # 产物的名称，基于 defaultConfig 中的 versionName
          path: app/build/outputs/apk/release/app-release.apk # Release APK 的路径（这里假设在构建后，文件名为 app-release.apk）
