name: Build Android APK

on:
  push:
    branches: [ main ]  # 触发分支（根据您的实际分支名修改）
  pull_request:         # 可选：PR 时触发
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APK_NAME: SEI804_VideoInfoOverlay_${{ github.run_number }}  # 使用运行号作为版本标识
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置 JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: 安装 Android SDK
      uses: android-actions/setup-android@v3
      with:
        # 指定需要的 SDK 组件
        packages: |
          platform-tools
          platforms;android-34
          build-tools;34.0.0

    - name: 授予 gradlew 执行权限
      run: chmod +x ./gradlew

    - name: 构建 Debug APK
      run: ./gradlew assembleDebug
      
    - name: 构建 Release APK
      if: github.ref == 'refs/heads/main'  # 仅在主分支构建 release
      run: ./gradlew assembleRelease
      env:
        # 从 GitHub Secrets 获取签名信息
        KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    - name: 上传 Debug APK
      uses: actions/upload-artifact@v4  # 更新为 v4
      with:
        name: ${{ env.APK_NAME }}_debug
        path: app/build/outputs/apk/debug/*.apk

    - name: 上传 Release APK
      if: github.ref == 'refs/heads/main'  # 仅在主分支上传 release
      uses: actions/upload-artifact@v4  # 更新为 v4
      with:
        name: ${{ env.APK_NAME }}_release
        path: app/build/outputs/apk/release/*.apk
